version: "3.8"

services:
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "12379:2379"
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      - easy-chat

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: easy-chat
    ports:
      - "13306:3306"
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    networks:
      - easy-chat

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    networks:
      - easy-chat
    command: redis-server --requirepass easy-chat --appendonly yes

  mongo:
    image: mongo:4.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: easy-chat
    ports:
      - "47017:27017"
    volumes:
      - ./components/mongo/data:/data/db
      - /etc/localtime:/etc/localtime
#    restart: always
    networks:
      - easy-chat
  kafka:
    image: 'bitnami/kafka:3.6.0'
    container_name: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      #      - 三个分区
      - KAFKA_CREATE_TOPICS=webook_binlog:3:1
      #      - 允许自动创建 topic，线上不要开启
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - easy-chat

volumes:
  etcd_data:
  mysql_data:
  redis_data:
  mongo_data:
  kafka_data:

networks:
  easy-chat:
    driver: bridge
